### PR TITLE
Fix issues running with python 3

### PR DESCRIPTION
**Pull request by tuxdna**
Fixes all the errors mentioned in https://github.com/gofed/gofedlib/issues/14

### CODE REVIEW

**Comment by tuxdna** [comment]
Please review

**Comment by ingvagabund** [comment]
@tuxdna can you rebase and squash the commits?

**Comment by tuxdna** [comment]
@ingvagabund Sure!

**Comment by tuxdna** [comment]
@ingvagabund Squashed them all :-)

**Comment by ingvagabund** [comment]
Failures not related to the PR -> merging

**Pull request merged**
