### PR TITLE
Fix indentation

### PR DESCRIPTION
**Pull request by tuxdna**
Fixes: https://github.com/gofed/gofedlib/issues/10

### CODE REVIEW

**Comment by fridex** [comment]
CI fail shouldn't be relevant here. @ingvagabund are we OK with merging this?

**Comment by ingvagabund** [comment]
The CI has been failing for a while. It's OK to merge.

**Comment by fridex** [comment]
@ingvagabund thanks 😉

**Comment by tuxdna** [comment]
@ingvagabund  thanks :+1:

**Pull request merged**
