### PR TITLE
Add travis config file

### PR DESCRIPTION
**Pull request by tuxdna**

### CODE REVIEW

**Comment by tuxdna** [comment]
@ingvagabund Seems like travis is not picking up the config file. I am not sure why this project default is set to Ruby on TravisCI - https://travis-ci.org/gofed/gofedlib/jobs/274973168

**Comment by fridex** [comment]
> Seems like travis is not picking up the config file.

See logs from Travis: `Could not find .travis.yml, using standard configuration.`. You've added .travis.y**a**ml.

**Comment by tuxdna** [comment]
@fridex: Yeah, this PR is already merged so the travis config file is already on master. The log I am sharing is from this PR - https://github.com/gofed/gofedlib/pull/15

**Comment by ingvagabund** [comment]
Just renamed to .travis file

**Comment by tuxdna** [comment]
@fridex @ingvagabund Yes, got it now. The file name shoud be changed.

@ingvagabund Unless you have already made the change I will go ahead and fix it.

**Comment by tuxdna** [comment]
@fridex @ingvagabund Alright, just saw this change https://github.com/gofed/gofedlib/commit/7efed6a58f1a577da3a963a7dd3d354c4c3dbd10

And yes, travis is now picking up the config file - https://travis-ci.org/gofed/gofedlib/jobs/274984305

👍

**Pull request merged**
